import './globals.css';
import Footer from './ui/Footer';
import NavigationMenu from './ui/NavigationMenu';

import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '900'],
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-black text-white `}>
        <NavigationMenu />
        <div className="mt-[80px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
