import HeroBanner from './ui/HeroBanner';
export const metadata = {
  title: 'Street Of Dreams',
  description: 'Generated by create next app',
};
export default function Home() {
  return (
    <main className="grid">
      <HeroBanner />
    </main>
  );
}
