import React from 'react';
import PageTitle from '../ui/PageTitle';
export const metadata = {
  title: 'Street Of Dreams | About Us',
  description: 'Generated by create next app',
};
function Page() {
  return (
    <div className="p-5 max-w-[1500px] mx-auto">
      <div className="flex justify-center py-5">
        <PageTitle text="About Us" />
      </div>
      <div className="mt-[50px]"></div>
    </div>
  );
}

export default Page;
